name: Shell
author: Daniel Millar
website: https://github.com/danielmillar
version: '${project.version}'
main: me.danielmillar.shell.Shell
api-version: 1.19

commands:
  shell:
    description: Shell command
    aliases: [sh]
  shellbook:
    description: Shellbook command
    aliases: [shb]
  shellreload:
    description: Shellreload command
    aliases: [shr]